# Generated by Django 4.1.3 on 2024-09-13 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProductManagement', '0002_alter_cardetails_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='cardetails',
            name='form_type',
            field=models.CharField(choices=[('draft', 'Draft'), ('completed', 'Completed')], default='draft', max_length=20),
        ),
    ]
