# Generated by Django 4.1.3 on 2024-09-14 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProductManagement', '0003_cardetails_form_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cardetails',
            name='status',
            field=models.CharField(default='live', max_length=80),
        ),
    ]
