# Generated by Django 4.1.3 on 2024-09-14 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProductManagement', '0004_alter_cardetails_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cardetails',
            name='status',
            field=models.CharField(default='live', max_length=80, null=True),
        ),
    ]
