# Generated by Django 4.1.3 on 2024-09-17 08:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ProductManagement', '0006_cardetails_is_draft'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cardetails',
            name='form_type',
        ),
    ]
