# Generated by Django 4.1.3 on 2024-09-19 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProductManagement', '0010_cardetails_previous_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cardetails',
            name='demand_price',
            field=models.CharField(max_length=80, null=True),
        ),
    ]
