# Generated by Django 4.1.3 on 2024-10-17 13:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ProductManagement', '0017_cardetails_review'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cardetails',
            name='status',
            field=models.CharField(default='processing', max_length=80, null=True),
        ),
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('cold', 'Cold'), ('warm', 'Warm'), ('hot', 'Hot')], default='cold', max_length=10)),
                ('visit_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('page_stay_duration', models.IntegerField(default=0)),
                ('explored_pages', models.IntegerField(default=0)),
                ('made_enquiry', models.BooleanField(default=False)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
