# Generated by Django 4.1.3 on 2024-10-21 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProductManagement', '0019_lead_viewed_car'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='user_type',
            field=models.CharField(default='Customer', max_length=10),
        ),
    ]
