# Generated by Django 4.1.3 on 2024-10-26 16:32

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ProductManagement', '0024_alter_notification_created_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notification',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterUniqueTogether(
            name='notification',
            unique_together={('user', 'message')},
        ),
    ]
