# Generated by Django 4.1.3 on 2024-09-12 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProductManagement', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cardetails',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
