# Generated by Django 4.1.3 on 2024-09-17 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProductManagement', '0005_alter_cardetails_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='cardetails',
            name='is_draft',
            field=models.BooleanField(default=False),
        ),
    ]
