# Generated by Django 4.1.3 on 2024-09-17 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProductManagement', '0007_remove_cardetails_form_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cardetails',
            name='car_year',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
