# Generated by Django 4.1.3 on 2024-09-17 09:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ProductManagement', '0008_alter_cardetails_car_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cardetails',
            name='abs',
            field=models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], default='Yes', max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='cardetails',
            name='accidental',
            field=models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], default='No', max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='cardetails',
            name='adjustable_steering',
            field=models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], default='No', max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='cardetails',
            name='alloy_wheel',
            field=models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], default='No', max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='cardetails',
            name='am_fm_radio',
            field=models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], default='No', max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='cardetails',
            name='android_car_play',
            field=models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], default='No', max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='cardetails',
            name='anti_theft_device',
            field=models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], default='No', max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='cardetails',
            name='aux_compatibility',
            field=models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], default='Yes', max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='cardetails',
            name='bluetooth',
            field=models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], default='No', max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='cardetails',
            name='color',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='cardetails',
            name='cruise_control',
            field=models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], default='No', max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='cardetails',
            name='ebd',
            field=models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], default='Yes', max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='cardetails',
            name='exchange',
            field=models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], default='No', max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='cardetails',
            name='extended_warranty',
            field=models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], default='No', max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='cardetails',
            name='finance',
            field=models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], default='No', max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='cardetails',
            name='front_parking_camera',
            field=models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], default='No', max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='cardetails',
            name='fuel_type',
            field=models.CharField(blank=True, choices=[('CNG', 'CNG'), ('Hybrid', 'Hybrid'), ('Diesel', 'Diesel'), ('Petrol', 'Petrol'), ('Electric', 'Electric'), ('LPG', 'LPG')], max_length=80, null=True),
        ),
        migrations.AlterField(
            model_name='cardetails',
            name='navigation_system',
            field=models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], default='No', max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='cardetails',
            name='ownership',
            field=models.CharField(blank=True, choices=[('1st Owner', '1st Owner'), ('2nd Owner', '2nd Owner'), ('3rd Owner', '3rd Owner'), ('4rd Owner', '4rd Owner')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='cardetails',
            name='power_steering',
            field=models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], default='No', max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='cardetails',
            name='rear_parking_camera',
            field=models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], default='No', max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='cardetails',
            name='rear_parking_sensor',
            field=models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], default='No', max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='cardetails',
            name='steering_control',
            field=models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], default='No', max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='cardetails',
            name='sun_roof',
            field=models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], default='No', max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='cardetails',
            name='usb_compatibility',
            field=models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], default='Yes', max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='cardetails',
            name='variant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='car_variant', to='ProductManagement.carvariant'),
        ),
        migrations.AlterField(
            model_name='cardetails',
            name='vehicle_warranty',
            field=models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], default='No', max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='cardetails',
            name='wireless_charger',
            field=models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], default='No', max_length=3, null=True),
        ),
    ]
