# Generated by Django 4.1.3 on 2024-09-18 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProductManagement', '0009_alter_cardetails_abs_alter_cardetails_accidental_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cardetails',
            name='previous_status',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
