# Generated by Django 4.1.3 on 2024-10-03 03:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ProductManagement', '0011_alter_cardetails_demand_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='DraftCarDetails',
            fields=[
                ('cardetails_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='ProductManagement.cardetails')),
                ('draft_saved_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Draft Car Detail',
                'verbose_name_plural': 'Draft Car Details',
            },
            bases=('ProductManagement.cardetails',),
        ),
    ]
