# Generated by Django 4.1.3 on 2024-10-05 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProductManagement', '0012_draftcardetails'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cardetails',
            name='car_year',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
