# Generated by Django 4.1.3 on 2024-10-05 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProductManagement', '0013_alter_cardetails_car_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cardetails',
            name='total_air_bag',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='cardetails',
            name='total_keys',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='cardetails',
            name='total_km_driven',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
