# Generated by Django 4.1.3 on 2024-10-14 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProductManagement', '0015_alter_warranty_warranty_period'),
    ]

    operations = [
        migrations.AlterField(
            model_name='warranty',
            name='warranty_period',
            field=models.PositiveIntegerField(),
        ),
    ]
