# Generated by Django 4.1.3 on 2024-10-24 13:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ProductManagement', '0022_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='car',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='schedule_car', to='ProductManagement.cardetails'),
        ),
    ]
