# Generated by Django 4.1.3 on 2024-10-28 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProductManagement', '0025_alter_notification_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='source',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
