# Generated by Django 4.2.2 on 2023-08-27 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserManagement', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='aadhar_card',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='customuser',
            name='firm_name',
            field=models.CharField(blank=True, max_length=90, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='pan_card',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
