# Generated by Django 4.1.3 on 2024-11-09 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserManagement', '0002_customuser_aadhar_card_customuser_firm_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='gst',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
